#question seed entities and KG facts path
ques_path: '../files/'

#data path
data_path: '../data/'

#model path for saving r-gcn models, etc
bert_model_path: '../model/bert_base_cased/'
model_path: '../model/'
elq_models_path: '../elq/'

#dictionaries and pretrained embedding files path
gcn_file_path: '../gcn_files/'

#benchmark file
train_data: 'train.json'
dev_data: 'dev.json'
test_data: 'test.json'

#property file
property_file: 'wikidata_property_dictionary.json'

#Wikipedia2Vec model path
wikipedia2vec: '../model/wikipedia2vec_trained'

#Number of Facts to be considered
top_f: 25

#Number of GSTs to be considered
top_g: 25

#Number of Temporal facts to be considered
top_t: 25